# Generated by Django 4.0.3 on 2022-03-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slobg_app', '0019_profile_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='volunteerrecord',
            name='activity',
            field=models.CharField(choices=[('Maintenance', 'Maintenance'), ('Administration', 'Administration'), ('Outreach', 'Outreach'), ('Education', 'Education'), ('Propagation', 'Propagation'), ('Other1', 'Other1')], max_length=256),
        ),
    ]
