# Generated by Django 4.0.3 on 2022-03-29 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slobg_app', '0020_eventmodel_alter_volunteerrecord_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerrecord',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='slobg_app.eventmodel'),
        ),
    ]
