# Generated by Django 4.0.3 on 2022-03-29 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slobg_app', '0022_alter_volunteerrecord_supervisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='areas_of_interest',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='emergency_contact_phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='esignature_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='group',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='medical_conditions',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photo_permission',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='volunteer_waiver_and_release',
        ),
        migrations.AlterField(
            model_name='volunteerrecord',
            name='supervisor',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ActivityChoice',
        ),
    ]
