# Generated by Django 4.0.3 on 2022-04-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcap373_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='waiver',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
