# Generated by Django 4.0.3 on 2022-04-26 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bcap373_app', '0003_alter_profile_waiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='supervisor',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_supervisor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='waiver',
            field=models.CharField(help_text="If you have this user's waiver on file, please indicate this in this box (and give a link to where it can be found, e.g. on Google Drive)", max_length=300, null=True),
        ),
    ]
