# Generated by Django 4.0.3 on 2022-04-26 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcap373_app', '0004_eventmodel_supervisor_alter_profile_waiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmodel',
            old_name='supervisor',
            new_name='event_supervisor',
        ),
    ]
