# Generated by Django 4.0.3 on 2022-04-27 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bcap373_app', '0005_rename_supervisor_eventmodel_event_supervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmodel',
            name='event_supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_supervisor', to=settings.AUTH_USER_MODEL),
        ),
    ]
