# Generated by Django 4.0.3 on 2022-04-29 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bcap373_app', '0007_alter_profile_waiver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='volunteerrecord',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
